modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="rottencreatures"
version="${version}"
displayName="Rotten Creatures"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rotten-creatures"
authors="RPorotos, KryzeDev"
description="test"
logoFile="banner.png"
[[dependencies.rottencreatures]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.rottencreatures]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
